### ISSUE TITLE
Translate pdf from spanish to english

### ISSUE THREAD

**Issue by xaca** [xaca/holamundo.co#1]
Translate pdf cheat sheet to english

**Comment by divayprakash** [comment]
@xaca I'd like to work on this. Could you provide some more detail?

**Comment by xaca** [comment]
@divayprakash Course, in the repo is a pdf file or a illustrator file with a programming cheat sheet in spanish. I need some contributors to translate this document to many language, starting with english. Here is the document if you want to see a digital version. https://goo.gl/iyoe5u Could you update directly the file, or update a text file with the translation for the amount of page that you could help. Thank you for be interesting in the project.

**Comment by divayprakash** [comment]
As far as I can understand the directory structure -
* `/ai` is the Adobe Illustrator files containing the images and the text linked together
* `/funetes` is the source folder containing the font sources
* `/imagenes` is the images folder
* `/imprimir` is the final output pdfs
* `/patrones` is the patterns folder

The issue is translating the text in the different slides into English. I can do that without any issues. Is it okay if I send a PR with a text file containing the text translated?

**Comment by xaca** [comment]
@divayprakash Yes the Pr is ok, only the text file with the translation. The project structure is correct.

**Comment by xaca** [comment]
@divayprakash Thank you for your help

**Comment by xaca** [comment]
We still need help with more slide pages, I have opened a new issue.

**Comment by divayprakash** [comment]
@xaca I will check back ASAP to help out if needed!

**Comment by xaca** [comment]
@divayprakash Thank you. Did you start this, we almost finish, would be nice a review for you. Because my native idiom is spanish, so maybe I have a lot of errors.
